name: weatherapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  get_it: ^8.0.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.0.13
  dio: ^5.7.0
  dartz: ^0.10.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/svg/
    - assets/gif/
    - assets/gif/loading.gif
    - .env

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 700
